version: '3'
services:
  web:
    container_name: api_server
    build: .
    command: python -u run.py
    ports:
      - 5000:5000
    volumes:
      - .:/app
    links:
      - datastore
  
  datastore:
    image: mongo:3.0.2
    ports:
      - 27017:27017