version: '3'
services:
  flaskapp:
    build: .
    image: kube/flask-demo:1.0
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app
  
  db:
    image: mongo:3.0.2
    ports:
      - 27017:27017