version: '3'
services:
  web:
    build: .
    image: kube/flask-demo:1.0
    ports:
      - 5000:5000
    volumes:
      - .:/app
    links:
      - datastore
  
  datastore:
    image: mongo:3.0.2
    ports:
      - 27017:27017